### ISSUE TITLE
Fixed in PonyTown

### ISSUE THREAD

**Issue by meowsynth** [qiraxyz/anti-afk#5]
Hi there,

I wanted to report that my anti-AFK script has stopped working on the main domain of pony.town. I'm currently using Windows 11 and the latest version of Google Chrome browser, and I haven't made any changes to my system. So it's highly likely that the problem is with the script itself.

Thank you for looking into this issue.

Best regards.

**Comment by meowsynth** [comment]
he start working again ig

honestly idk whats happend

**Comment by qiraxyz** [comment]
> he start working again ig
> 
> honestly idk whats happend

sorry late answer.

U can Just restart the web.
