### ISSUE TITLE
pony.town, fixed probably

### ISSUE THREAD

**Issue by meowsynth** [qiraxyz/anti-afk#7]
check pls, not working for me from yesterday

**Comment by meowsynth** [comment]
again not working

**Comment by qiraxyz** [comment]
show me the proof

**Comment by meowsynth** [comment]
<img width="713" alt="image" src="https://github.com/qiraxyz/anti-afk/assets/70239765/1022e6e1-acb6-4982-924e-49c77e0136ca">
<img width="326" alt="image" src="https://github.com/qiraxyz/anti-afk/assets/70239765/be824600-1cb6-475a-be3f-236a40e48443">

**Comment by qiraxyz** [comment]
try the newest update tutorial in my yt : https://youtu.be/124Ua5oJwpo

or u can try this https://github.com/qiraxyz/anti-afk/releases/tag/release

**Comment by qiraxyz** [comment]
![w](https://github.com/qiraxyz/anti-afk/assets/79699856/95718832-5f8e-411f-9a66-64ddbd57e2ff)
![e3](https://github.com/qiraxyz/anti-afk/assets/79699856/a5db1b4b-781d-4130-8dcc-4cdcbb86945f)
![323](https://github.com/qiraxyz/anti-afk/assets/79699856/7e8dd549-b92a-4d9a-b293-952feb329690)

u don't need to open inspector cmd to use anti afk script.

**Comment by meowsynth** [comment]
Video unavailable
This video contains content from SME, who has blocked it in your country on copyright grounds

> try the newest update tutorial in my yt : https://youtu.be/124Ua5oJwpo
> 
> or u can try this https://github.com/qiraxyz/anti-afk/releases/tag/release

**Comment by meowsynth** [comment]
<img width="320" alt="image" src="https://github.com/qiraxyz/anti-afk/assets/70239765/ee04ea01-5bae-48e0-8042-84eae1e7d72c">
alr, i use it from the new guide

**Comment by meowsynth** [comment]
still not working =(
<img width="633" alt="image" src="https://github.com/qiraxyz/anti-afk/assets/70239765/6b9243cc-324e-45f2-979a-ec0cedd6015a">
in new chrome resource economy feature i put pony.town to always working page

**Comment by qiraxyz** [comment]
i can't understand russian language can u please make it english

**Comment by qiraxyz** [comment]
https://youtu.be/-MMea9T9g0Q

here. the new tutorial.

**Comment by meowsynth** [comment]
> 



> https://youtu.be/-MMea9T9g0Q
> 
> here. the new tutorial.

okkk, ill try
